### ISSUE TITLE
migration cli issues

### ISSUE THREAD

**Issue by Akmal-Keisin** [crudbooster/superframework#1]
hi sir, i found some issues when start to using the migration cli. the command return

here is my command : php super make:migration students

and here is the issues :

![Screenshot (200)](https://user-images.githubusercontent.com/57882204/169195495-38fab7f3-bcbf-406c-ae01-98d1a900087a.png)

i don't even write . in the command but its return like that. hope this issue can help you to debug your framework next sir.

**Comment by fherryfherry** [comment]
Please update version bro @Akmal-Keisin
